/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author alex.negrean
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Statement st = null;
    
    public FastCash() {
        initComponents();
    }
    
    int MyAccNum;
    public FastCash(int AccNum){
        initComponents();
        MyAccNum = AccNum;
        GetBalance();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BalanceLb = new javax.swing.JLabel();
        Amount100Btn = new javax.swing.JButton();
        Amount1000Btn = new javax.swing.JButton();
        Amount400Btn = new javax.swing.JButton();
        Amount200Btn = new javax.swing.JButton();
        AnotherBtn = new javax.swing.JButton();
        Amount500Btn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        BalanceLb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Amount100Btn.setText("100");
        Amount100Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Amount100BtnMouseClicked(evt);
            }
        });

        Amount1000Btn.setText("1000");
        Amount1000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Amount1000BtnMouseClicked(evt);
            }
        });

        Amount400Btn.setText("400");
        Amount400Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Amount400BtnMouseClicked(evt);
            }
        });

        Amount200Btn.setText("200");
        Amount200Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Amount200BtnMouseClicked(evt);
            }
        });

        AnotherBtn.setText("ANOTHER AMOUNT");
        AnotherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnotherBtnMouseClicked(evt);
            }
        });

        Amount500Btn.setText("500");
        Amount500Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Amount500BtnMouseClicked(evt);
            }
        });

        BackBtn.setText("BACK");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account Balance :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Amount400Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Amount1000Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Amount100Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Amount200Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnotherBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Amount500Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BalanceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BalanceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount100Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount200Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount400Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount500Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount1000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnotherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int oldBalance;
    private void GetBalance(){
        String query = "SELECT * FROM accounttbl WHERE accnum="+MyAccNum+"";
        try{
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
            st = con.createStatement();
            rs = st.executeQuery(query);
            if(rs.next()){
                oldBalance = rs.getInt(8);
                BalanceLb.setText(""+oldBalance);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void Amount1000BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amount1000BtnMouseClicked
        if(oldBalance >= 1000){
            try{
                String query = "UPDATE accounttbl SET balance=? WHERE accnum=?";
                con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1,oldBalance - 1000);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this,"You have withdraw 1000");
                    new FastCash(MyAccNum).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insufficient funds");
        }
    }//GEN-LAST:event_Amount1000BtnMouseClicked

    private void Amount200BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amount200BtnMouseClicked
        if(oldBalance >= 200){
            try{
                String query = "UPDATE accounttbl SET balance=? WHERE accnum=?";
                con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1,oldBalance - 200);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this,"You have withdraw 200");
                    new FastCash(MyAccNum).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insufficient funds");
        }
    }//GEN-LAST:event_Amount200BtnMouseClicked

    private void AnotherBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnotherBtnMouseClicked
        new Withdraw(MyAccNum).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnotherBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainMenu(MyAccNum).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void Amount100BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amount100BtnMouseClicked
        if(oldBalance >= 100){
            try{
                String query = "UPDATE accounttbl SET balance=? WHERE accnum=?";
                con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1,oldBalance - 100);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this,"You have withdraw 100");
                    new FastCash(MyAccNum).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insufficient funds");
        }
    }//GEN-LAST:event_Amount100BtnMouseClicked

    private void Amount400BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amount400BtnMouseClicked
        if(oldBalance >= 400){
            try{
                String query = "UPDATE accounttbl SET balance=? WHERE accnum=?";
                con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1,oldBalance - 400);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this,"You have withdraw 400");
                    new FastCash(MyAccNum).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insufficient funds");
        }
    }//GEN-LAST:event_Amount400BtnMouseClicked

    private void Amount500BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amount500BtnMouseClicked
        if(oldBalance >= 500){
            try{
                String query = "UPDATE accounttbl SET balance=? WHERE accnum=?";
                con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/ATMDb","postgres","Parola1A");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1,oldBalance - 500);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this,"You have withdraw 500");
                    new FastCash(MyAccNum).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insufficient funds");
        }
    }//GEN-LAST:event_Amount500BtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Amount1000Btn;
    private javax.swing.JButton Amount100Btn;
    private javax.swing.JButton Amount200Btn;
    private javax.swing.JButton Amount400Btn;
    private javax.swing.JButton Amount500Btn;
    private javax.swing.JButton AnotherBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel BalanceLb;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
